---
title: "R Notebook"
output: html_notebook
---

```{r}
#1. Statistics for summarizing your sample
#define some variable
x<-c(1.3,0.9,1.1,3.2,1.6,1.7,0.8,1.0,1.4,1.5,1.3,1.5,1.7)
#print different statistics from this variable
print(c('Mean:',mean(x)))
print(c('Standard deviation:',sd(x)))
print(c('Median:',median(x)))
print(c('Interquartile range:',IQR(x)))
print(c('Minimum:',min(x)))
print(c('Maximum:',max(x)))
print(c('Range:',max(x)-min(x)))
```

```{r}
#2. Visualization
#define a variable
x<-c(1.3,0.9,1.1,3.2,1.6,1.7,0.8,1.0,1.4,1.5,1.3,1.5,1.7)
#plot a histogram, boxplot, and density plot
hist(x,col='lightblue')
boxplot(x,col='white')
plot(density(x),col='blue')
```

```{r}
#3. Shapiro-Wilk normality test
#define a variable
x<-c(1.3,0.9,1.1,3.2,1.6,1.7,0.8,1.0,1.4,1.5,1.3,1.5,1.7)
#print the output of the test for the variable
print(shapiro.test(x))
```

```{r}
#4. False discovery rate correction
#Suppose that you have the following p-values:
p_values<-c(0.03,0.00045,0.01,0.31,0.56,0.97,0.00001)
#print the corrected p-values
print(c('The corrected p-values:',p.adjust(p_values)))
```

```{r}
#5. Paired and unpaired tests
#define two variables
x<-c(1.3,0.9,1.1,3.2,1.6,1.7,0.8,1.0,1.4,1.5,1.3,1.5,1.7)
y<-c(1.4,1.8,1.3,3.3,1.5,1.7,0.9,1.1,1.5,1.7,1.5,1.3,1.9)
print(t.test(x,y,paired=TRUE))
print(wilcox.test(x,y,paired=TRUE))
print(t.test(x,y,paired=FALSE))
print(wilcox.test(x,y,paired=FALSE))
#To know which test to use, remember to check normality and consider if data is paired or not!
```

```{r}
#6. Tests comparing multiple groups
x<-c(1.3,0.9,1.1,3.2,1.6,1.7,0.8,1.0,1.4,1.5,1.3,1.5,1.7)
y<-c(1.4,1.8,1.3,3.3,1.5,1.7,0.9,1.1,1.5,1.7,1.5,1.3,1.9)
z<-c(1.1,0.7,1.0,3.1,1.3,1.8,0.5,0.6,0.4,0.5,0.3,1.5,1.1)
#create one vector containing values of x, y, and z
values<-c(x,y,z)
#create a corresponding vector with indices 1, 2, 3 indicating whether
#a given value belongs to x, y, or z
groups<-c(rep(1,length(x)),rep(2,length(y)),rep(3,length(z)))
#fit ANOVA model (group indices vs values)
model<-aov(values~groups)
print('ANOVA')
print(summary(model))
#in the print, the p-value is denoted by Pr(>F)
#Print the Kruskal-Wallis test results
print(kruskal.test(values~groups))
#To know which test to use, remember to check normality!
```

```{r}
#7. Correlation tests
x<-c(1.3,0.9,1.1,3.2,1.6,1.7,0.8,1.0,1.4,1.5,1.3,1.5,1.7)
y<-c(1.4,1.8,1.3,3.3,1.5,1.7,0.9,1.1,1.5,1.7,1.5,1.3,1.9)
print(cor.test(x,y,method='pearson'))
print(cor.test(x,y,method='spearman'))
#To know which test to use, remember to check normality!
```

```{r}
#8. Tests for a contingency table
#Define a contingency table as numpy array
x<-matrix(data=c(31,13,89,14,97,35),nrow=2,ncol=3)
print(x)
#Print the output of the chi-squared test
print(chisq.test(x))
#Define another 2*2 table
y<-matrix(data=c(10,3,7,1),nrow=2,ncol=2)
print(y)
#Print the output of Fisher's exact test
print(fisher.test(y))
```

